### ISSUE TITLE
Does Rx-Angular/template work? 

### ISSUE THREAD

**Issue by BioPhoton** [friedrich-ulrich/ngrx-test-v10#1]
Did you try to use rx-angular/template?

I did quite some progress compared to my implementation in ngrx. If it is also not working just open an issue thete any we fix it for you.

https://github.com/rx-angular/rx-angular/blob/master/libs/template/README.md

Let me know if it helps

**Comment by friedrich-ulrich** [comment]
@BioPhoton It does not work with that libs as well. We've commited the changes to the branch rx-angular.

**Comment by friedrich-ulrich** [comment]
works with angular 10.2.0
